version: '3.1'
services:
  flaskapp:
    image: dockergeethaacc/flaskcal:5
    restart: always
    ports:
    - 3000:3000
    networks:
    - flaskappbridge
networks:
  flaskappbridge:
    driver: bridge
