version: '3.1'
services:
  flaskapp:
    image: dockergeethaacc/flaskcal:2
    restart: always
    ports:
    - 3010:3000
    networks:
    - flaskappbridge
networks:
  flaskappbridge:
    driver: overlay
